
// © copyright 2026 Roly QH
// This hook is triggered before a new record is created in the "posts" collection.
// It automatically generates a slug from the title if the slug field is empty.
// The slug is generated by converting the title to lowercase, removing diacritics, replacing non-alphanumeric characters with hyphens, and trimming leading/trailing hyphens.


// en pocketbase esta funcion onRecordBeforeCreateRequest((e) => { ... }) ya no existe en la version +v0.23+ y se reemplazo por onRecordCreateRequest((e) => { ... }) que se ejecuta despues de que el registro es creado, pero antes de que sea guardado en la base de datos, por lo que podemos modificar el registro antes de que sea guardado en la base de datos
//fue actulizada por onRecordCreateRequest((e) => { ... })

onRecordCreateRequest((e) => {
    const record = e.record;
    // Check if the slug field is empty or not set
    // If it is empty, generate a slug from the title
    if (!record.get("slug") || record.get("slug") === "") {
        const title = record.get("title") || "";
        const slug = title
            .toLowerCase()
            // Remove diacritics (accents) from the title
            // This is done using Unicode normalization and a regular expression to remove combining diacritical marks
            
            .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-+|-+$/g, "");
            // Set the generated slug to the record
        record.set("slug", slug);
    }
    // Continue with the request new version pocketbase +v0.23+
    e.next();
}, "posts")
