
// © copyright 2026 Roly QH
// This hook is triggered before a new record is created in the "posts" collection.
// It automatically generates a slug from the title if the slug field is empty.
// The slug is generated by converting the title to lowercase, removing diacritics, replacing non-alphanumeric characters with hyphens, and trimming leading/trailing hyphens.


// en pocketbase esta funcion onRecordBeforeCreateRequest((e) => { ... }) ya no existe en la version +v0.23+ y se reemplazo por onRecordCreateRequest((e) => { ... }) que se ejecuta despues de que el registro es creado, pero antes de que sea guardado en la base de datos, por lo que podemos modificar el registro antes de que sea guardado en la base de datos
//fue actulizada por onRecordCreateRequest((e) => { ... })

onRecordCreateRequest((e) => {
    const record = e.record;
    // Check if the slug field is empty or not set
    // If it is empty, generate a slug from the title
    if (!record.get("slug") || record.get("slug") === "") {
        const title = record.get("title") || "";
        const slug = title
            .toLowerCase()
            // Remove diacritics (accents) from the title
            // This is done using Unicode normalization and a regular expression to remove combining diacritical marks
            
            .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-+|-+$/g, "");
            // Set the generated slug to the record
        record.set("slug", slug);
    }

    const content = record.get("content") || "";
    const plainText = content.replace(/<[^>]*>/g, " ");
    const wordCount = plainText.trim().split(/\s+/).filter(w => w.length > 0).length;
    const minutes = Math.max(1, Math.ceil(wordCount / 200));
    record.set("reading_time", minutes);

    if (!record.get("views")) {
        record.set("views", 0);
    }


    // Continue with the request new version pocketbase +v0.23+
    e.next();
}, "posts")


// This hook is triggered before an existing record is updated in the "posts" collection.
// It calculates the reading time based on the content field and updates the reading_time field accordingly.
onRecordUpdateRequest((e) => {
    const record = e.record;

    const content = record.get("content") || "";
    const plainText = content.replace(/<[^>]*>/g, " ");
    const wordCount = plainText.trim().split(/\s+/).filter(w => w.length > 0).length;
    const minutes = Math.max(1, Math.ceil(wordCount / 200));
    record.set("reading_time", minutes);

    e.next();
}, "posts")



// This hook is triggered when a POST request is made to the "/api/posts/{id}/view" endpoint.
routerAdd("POST", "/api/posts/{id}/view", (e) => {
    // Get the post ID from the request path
    const id = e.request.pathValue("id");

    try {
        const record = e.app.findRecordById("posts", id);
        record.set("views", (record.get("views") || 0) + 1);
        e.app.save(record);
    } catch (err) {
        return e.json(404, { error: "Post not found" });
    }

    return e.json(200, { success: true });
});
